__title__ = 'razor-proxy'
__description__ = 'High Performance Proxy Server'
__url__ = 'https://www.github.com/xsxo/razor-proxy'
__version__ = '0.1'
__author__ = 'xsxo'
__license__ = 'Apache-2.0'
__copyright__ = 'Copyright xsxo'